### ISSUE TITLE
Cannot reproduce results from 2D ERT example

### ISSUE THREAD

**Issue by mikkelbue** [gimli-org/gimli#319]
### Problem description

I am running the [2D ERT example ](https://www.pygimli.org/_examples_auto/3_dc_and_ip/plot_01_ert_2d_mod_inv.html#sphx-glr-examples-auto-3-dc-and-ip-plot-01-ert-2d-mod-inv-py) to try and make friends with pyGIMLi, and learn about ERT.

Using the unstructured grid, it works as expected, but with the structured grid, I cannot reproduce the results from the examples web page. Please find a plot of my results attached. I have been trying to play around with the inversion regularisation parameter `lam` but to no avail.

My apologies, if this is a very silly question, I am not very familiar with ERT.

![ert_result](https://user-images.githubusercontent.com/7152798/120547573-99cfd000-c3f1-11eb-9cc2-723653ea9756.png)

### Your environment

**Operating system**: Ubuntu Linux 20.04
**Python version**: Python 3.8.5
**pyGIMLi version**: 1.2.1+8.g292d1d0d
**Way of installation**: From source

### Steps to reproduce

I just ran the example and saved the output to the attached file:

```
python3 plot_01_ert_2d_mod_inv.py
```

### Expected behavior

I would like to reproduce the figures from the examples page.

### Actual behavior

The inversion on the structured grid does not seem to capture the low resistivity blob very well, and high resistivity appears to "bleed".

**Comment by carsten-forty2** [comment]
ah ..  this a issue regarding a change of the default boundary markers in the grid generation. 
Its already fixed in 'dev' branch and should be also in master and release. If you build from source an update should be sufficient.

**Comment by mikkelbue** [comment]
Hi @carsten-forty2 
Thanks for your response. I now tried to install the dev-branch (`pg.__version__` returns 1.2.1+49.g927620d6), but I still get the same result. These are the inversion domain parameters:
```
inversionDomain = pg.createGrid(x=np.linspace(start=-18, stop=18, num=33),
                                y=-pg.cat([0], pg.utils.grange(0.5, 8, n=8)),
                                marker=2)
grid = pg.meshtools.appendTriangleBoundary(inversionDomain, marker=1,
                                           xbound=50, ybound=50)
model = mgr.invert(data, mesh=grid, lam=20, verbose=True)
```

**Comment by carsten-forty2** [comment]
yes .. my fault .. there was a missing direction switch in the example itself. I commited the working example in 'release'.

y-direction needs to be in ascending order.

```
y=-pg.cat([0], pg.utils.grange(0.5, 8, n=5))[::-1]
```

**Comment by mikkelbue** [comment]
Ah, amazing! That makes sense. Thank you! 

Sorry, I didn't realise that there was change was in the script, I thought it was something with the backend.
